# Generated by Django 4.1.4 on 2023-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderimage/')),
            ],
            options={
                'verbose_name': 'SliderImage',
                'verbose_name_plural': 'SliderImages',
                'ordering': ['id'],
            },
        ),
    ]
