# Generated by Django 4.1.4 on 2023-04-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aboutus_options_alter_sliderimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='testimonialsimage/')),
                ('discriptions', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
