# Generated by Django 4.1.4 on 2023-04-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['-id'], 'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
