# Generated by Django 4.1.4 on 2023-04-21 07:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_testimonials_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequently_Asked_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('discriptions', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
                'ordering': ['-id'],
            },
        ),
    ]
