# Generated by Django 4.1.4 on 2023-04-23 07:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='university_name', unique=True)),
            ],
            options={
                'verbose_name': 'University In Canada',
                'verbose_name_plural': 'universities In Canada',
                'ordering': ['id'],
            },
        ),
    ]
