# Generated by Django 4.1.4 on 2023-04-23 07:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='unversityimage/')),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='university', to='app.university')),
            ],
            options={
                'verbose_name': 'University Detail',
                'verbose_name_plural': 'Universities Details',
                'ordering': ['-id'],
            },
        ),
    ]
