# Generated by Django 4.1.4 on 2023-04-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_universitydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitydetails',
            name='university_name',
        ),
    ]
