# Generated by Django 4.1.4 on 2023-04-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_universitydetails_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydetails',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='app.university'),
        ),
    ]
