# Generated by Django 4.1.4 on 2023-04-25 07:25

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customerquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servicesimage/')),
                ('service_title', models.CharField(max_length=150)),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('service_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='service_title', unique=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
            },
        ),
    ]
