# Generated by Django 4.1.4 on 2023-04-25 07:28

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_services_options_remove_services_service_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_slug',
            field=autoslug.fields.AutoSlugField(default=None, unique=True, verbose_name=models.CharField(max_length=150)),
        ),
        migrations.AlterField(
            model_name='services',
            name='discriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
