# Generated by Django 4.1.4 on 2023-04-25 07:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_services_service_slug_alter_services_discriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='service_title', unique=True),
        ),
    ]
