# Generated by Django 4.1.4 on 2023-04-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='meta_author',
            new_name='author',
        ),
    ]
