# Generated by Django 4.1.4 on 2023-04-27 05:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_meta_author_settings_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='discriptions',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
