# Generated by Django 4.1.4 on 2023-04-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_sliderimage_discriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequently_asked_question',
            options={'ordering': ['-id'], 'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
    ]
