# Generated by Django 4.1.4 on 2023-04-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_contact_info_headoffice_branchoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='app.contact_info'),
        ),
        migrations.AlterField(
            model_name='headoffice',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_informations', to='app.contact_info'),
        ),
    ]
