# Generated by Django 4.1.4 on 2023-04-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_branchoffice_contact_alter_headoffice_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_info',
            old_name='location_url',
            new_name='map_url',
        ),
        migrations.AddField(
            model_name='contact_info',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
