# Generated by Django 4.1.4 on 2023-04-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_location_url_contact_info_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
