# Generated by Django 4.1.4 on 2023-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_contact_info_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='facebook_page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='insta_page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
