# Generated by Django 4.1.4 on 2023-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_contact_info_facebook_page_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
