# Generated by Django 4.1.4 on 2023-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_ourteam_facebook_url_ourteam_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='phone_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='phone_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='headoffice',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
